import { Dropdown, Button, message } from 'antd'
import {
  ExportOutlined,
  FileMarkdownOutlined,
  FileTextOutlined,
  CopyOutlined,
  CodeOutlined,
} from '@ant-design/icons'
import { useSqlStore } from '@/store/useSqlStore'

function generateMarkdown(result: import('@/types/sql').SQLAnalysisResult): string {
  const lines: string[] = []
  lines.push('# SQL 解析报告\n')
  lines.push(`**SQL 类型**: ${result.statementType}`)
  lines.push(`**方言**: ${result.dialect}\n`)

  lines.push('## 概览\n')
  lines.push(`| 指标 | 值 |`)
  lines.push(`|---|---|`)
  lines.push(`| 涉及表数 | ${result.summary.tableCount} |`)
  lines.push(`| JOIN 数量 | ${result.summary.joinCount} |`)
  lines.push(`| 查询字段数 | ${result.summary.fieldCount} |`)
  lines.push(`| WHERE 条件数 | ${result.summary.whereCount} |`)
  lines.push(`| 复杂度 | ${result.summary.complexity} |`)
  lines.push('')

  if (result.tables.length > 0) {
    lines.push('## 涉及表\n')
    lines.push('| 表名 | 别名 | 角色 |')
    lines.push('|---|---|---|')
    for (const t of result.tables) {
      lines.push(`| ${t.name} | ${t.alias || '-'} | ${t.role} |`)
    }
    lines.push('')
  }

  if (result.joins.length > 0) {
    lines.push('## JOIN 关系\n')
    for (const j of result.joins) {
      lines.push(`- **${j.type}** ${j.rightTable}`)
      for (const c of j.conditions) {
        lines.push(`  - ON \`${c.left}\` ${c.operator} \`${c.right}\``)
      }
    }
    lines.push('')
  }

  if (result.fields.length > 0) {
    lines.push('## 查询字段\n')
    lines.push('| 输出名 | 来源表 | 表达式 | 类型 |')
    lines.push('|---|---|---|---|')
    for (const f of result.fields) {
      lines.push(`| ${f.outputName} | ${f.sourceTable || '-'} | ${f.expression} | ${f.fieldType} |`)
    }
    lines.push('')
  }

  if (result.whereTree) {
    lines.push('## WHERE 条件\n')
    const writeNode = (node: import('@/types/sql').ConditionNode, depth: number) => {
      const indent = '  '.repeat(depth)
      if (node.type === 'CONDITION') {
        lines.push(`${indent}- \`${node.expr}\``)
      } else {
        lines.push(`${indent}- **${node.type}**`)
        for (const child of node.children || []) {
          writeNode(child, depth + 1)
        }
      }
    }
    writeNode(result.whereTree, 0)
    lines.push('')
  }

  if (result.risks.length > 0) {
    lines.push('## 风险提示\n')
    for (const r of result.risks) {
      const icon = r.level === 'danger' ? '!!' : r.level === 'warning' ? '!' : 'i'
      lines.push(`- [${icon}] **${r.type}**: ${r.message}`)
      lines.push(`  - 建议: ${r.suggestion}`)
    }
    lines.push('')
  }

  lines.push(`\n---\n*Generated by SQL Lens*`)
  return lines.join('\n')
}

export default function ExportMenu() {
  const result = useSqlStore((s) => s.result)
  const rawText = useSqlStore((s) => s.rawText)

  if (!result) return null

  const handleExport = (key: string) => {
    switch (key) {
      case 'markdown': {
        const md = generateMarkdown(result)
        const blob = new Blob([md], { type: 'text/markdown' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = 'sql-lens-report.md'
        a.click()
        URL.revokeObjectURL(url)
        message.success('Markdown 报告已下载')
        break
      }
      case 'json': {
        const json = JSON.stringify(result, null, 2)
        const blob = new Blob([json], { type: 'application/json' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = 'sql-lens-result.json'
        a.click()
        URL.revokeObjectURL(url)
        message.success('JSON 数据已下载')
        break
      }
      case 'sql': {
        const sql = result.formattedSql || result.restoredSql || result.rawSql
        const blob = new Blob([sql], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = 'query.sql'
        a.click()
        URL.revokeObjectURL(url)
        message.success('SQL 文件已下载')
        break
      }
      case 'copy-md': {
        const md = generateMarkdown(result)
        navigator.clipboard.writeText(md)
        message.success('Markdown 已复制到剪贴板')
        break
      }
      case 'copy-json': {
        const json = JSON.stringify(result, null, 2)
        navigator.clipboard.writeText(json)
        message.success('JSON 已复制到剪贴板')
        break
      }
      case 'copy-sql': {
        const sql = result.formattedSql || result.restoredSql || result.rawSql
        navigator.clipboard.writeText(sql)
        message.success('SQL 已复制到剪贴板')
        break
      }
    }
  }

  const items = [
    {
      key: 'download',
      label: '下载文件',
      type: 'group' as const,
      children: [
        { key: 'markdown', icon: <FileMarkdownOutlined />, label: '下载 Markdown 报告' },
        { key: 'json', icon: <FileTextOutlined />, label: '下载 JSON 数据' },
        { key: 'sql', icon: <CodeOutlined />, label: '下载格式化 SQL' },
      ],
    },
    {
      key: 'clipboard',
      label: '复制到剪贴板',
      type: 'group' as const,
      children: [
        { key: 'copy-md', icon: <CopyOutlined />, label: '复制 Markdown' },
        { key: 'copy-json', icon: <CopyOutlined />, label: '复制 JSON' },
        { key: 'copy-sql', icon: <CopyOutlined />, label: '复制 SQL' },
      ],
    },
  ]

  return (
    <Dropdown menu={{ items, onClick: ({ key }) => handleExport(key) }} trigger={['click']}>
      <Button size="small" icon={<ExportOutlined />}>
        导出
      </Button>
    </Dropdown>
  )
}
